/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        bg: "var(--color-background)",
        "bg-hover": "var(--color-background-hover)",
        text: "var(--color-text)",
        primary: "var(--color-primary)",

        "instagram-text": "var(--instagram-text)",
        "instagram-bg": "var(--instagram-bg)",
        "instagram-ring": "var(--instagram-ring)",
        "telegram-text": "var(--telegram-text)",
        "telegram-bg": "var(--telegram-bg)",
        "telegram-ring": "var(--telegram-ring)",
        "twitter-text": "var(--twitter-text)",
        "twitter-bg": "var(--twitter-bg)",
        "twitter-ring": "var(--twitter-ring)",
        "linkedin-text": "var(--linkedin-text)",
        "linkedin-bg": "var(--linkedin-bg)",
        "linkedin-ring": "var(--linkedin-ring)",
        "youtube-text": "var(--youtube-text)",
        "youtube-bg": "var(--youtube-bg)",
        "youtube-ring": "var(--youtube-ring)",
        "aparat-text": "var(--aparat-text)",
        "aparat-bg": "var(--aparat-bg)",
        "aparat-ring": "var(--aparat-ring)",
        "facebook-text": "var(--facebook-text)",
        "facebook-bg": "var(--facebook-bg)",
        "facebook-ring": "var(--facebook-ring)",
        "pinterest-text": "var(--pinterest-text)",
        "pinterest-bg": "var(--pinterest-bg)",
        "pinterest-ring": "var(--pinterest-ring)",
        "reddit-text": "var(--reddit-text)",
        "reddit-bg": "var(--reddit-bg)",
        "reddit-ring": "var(--reddit-ring)",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
  purge: {
    options: {
      safelist: [
        "text-instagram-text",
        "bg-instagram-bg",
        "ring-instagram-ring",
        "text-telegram-text",
        "bg-telegram-bg",
        "ring-telegram-ring",
        "text-twitter-text",
        "bg-twitter-bg",
        "ring-twitter-ring",
        "text-linkedin-text",
        "bg-linkedin-bg",
        "ring-linkedin-ring",
        "text-youtube-text",
        "bg-youtube-bg",
        "ring-youtube-ring",
        "text-aparat-text",
        "bg-aparat-bg",
        "ring-aparat-ring",
        "text-facebook-text",
        "bg-facebook-bg",
        "ring-facebook-ring",
        "text-pinterest-text",
        "bg-pinterest-bg",
        "ring-pinterest-ring",
        "text-reddit-text",
        "bg-reddit-bg",
        "ring-reddit-ring",
      ],
    },
  },
}
