name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set date and time variable
        run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
      
      - name: Build Docker image
        run: |
          docker build -t social-dash-frnt:$IMAGE_TAG .
      
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image
        run: docker tag social-dash-frnt:$IMAGE_TAG ${{ secrets.DOCKER_USERNAME }}/social-dash-frnt:$IMAGE_TAG

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/social-dash-frnt:$IMAGE_TAG

      - name: Tag Docker image
        run: docker tag social-dash-frnt:$IMAGE_TAG ${{ secrets.DOCKER_USERNAME }}/social-dash-frnt:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/social-dash-frnt:latest
